//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int id_order { get; set; }
        public int id_product { get; set; }
        public int count { get; set; }
        public decimal cost { get; set; }
        public int id_pvz { get; set; }
        public int id_client { get; set; }
        public System.DateTime data_zakaza { get; set; }
        public System.DateTime data_dostavki { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Parfum Parfum { get; set; }
        public virtual punkt_vidachi punkt_vidachi { get; set; }
    }
}
