//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workers
    {
        public int id_worker { get; set; }
        public int id_akk { get; set; }
        public string role { get; set; }
        public string name_w { get; set; }
        public string surname_w { get; set; }
        public string patronymic_w { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
